---
- hosts: '{{ hosts }}'
  strategy: free
  gather_facts: no
  roles:
  - { role: apigee-opdk-setup-apigee-user, tags: ['apigee-user', 'apigee-pre-req'] }
  - { role: apigee-opdk-setup-os-limits, tags: ['apigee-pre-req', 'apigee-tuning'] }
  - { role: apigee-opdk-setup-openjdk, tags: ['apigee-pre-req', 'openjdk']}
  - { role: apigee-opdk-setup-java-home, tags: ['apigee-pre-req', 'java-home']}
  - { role: apigee-opdk-setup-bootstrap, tags: ['apigee-pre-req', 'apigee-bootstrap'] }
  - { role: apigee-opdk-setup-silent-installation-config, tags: ['apigee-pre-req', 'apigee-silent-config'] }
