---

- hosts: localhost

  tasks:
  - name: Ensure SSH key is generated of control-server
    command: ssh-keygen -t rsa -f /root/.ssh/id_rsa -N ''
    args:
      creates: /root/.ssh/id_rsa

- hosts: all

  tasks:
  - selinux:
     policy: targeted
     state: permissive

  - name: Enable EPEL Repo
    yum:
     name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
     state: present

