---
ansible_config: ~/.ansible
apigee_config: ~/.apigee
playbook_workspace: ~/apigee-workspace/apigee-opdk-playbook-workspace
role_workspace: ~/apigee-workspace/apigee-opdk-role-workspace
host_repo: https://github.com/carlosfrias
configuration_folders:
- '{{ ansible_config }}/configurations'
- '{{ ansible_config }}/inventory'
- '{{ ansible_config }}/tmp/logs'
- '{{ apigee_config }}'
- '{{ playbook_workspace }}'
- '{{ role_workspace }}'